// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: analytics.proto
#ifndef GRPC_analytics_2eproto__INCLUDED
#define GRPC_analytics_2eproto__INCLUDED

#include "analytics.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace edgify {

class AnalyticsService final {
 public:
  static constexpr char const* service_full_name() {
    return "edgify.AnalyticsService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CreateEvent(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest& request, ::edgify::CreateAnalyticsEventResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::edgify::CreateAnalyticsEventResponse>> AsyncCreateEvent(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::edgify::CreateAnalyticsEventResponse>>(AsyncCreateEventRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::edgify::CreateAnalyticsEventResponse>> PrepareAsyncCreateEvent(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::edgify::CreateAnalyticsEventResponse>>(PrepareAsyncCreateEventRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void CreateEvent(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest* request, ::edgify::CreateAnalyticsEventResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void CreateEvent(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest* request, ::edgify::CreateAnalyticsEventResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void CreateEvent(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest* request, ::edgify::CreateAnalyticsEventResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::edgify::CreateAnalyticsEventResponse>* AsyncCreateEventRaw(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::edgify::CreateAnalyticsEventResponse>* PrepareAsyncCreateEventRaw(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CreateEvent(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest& request, ::edgify::CreateAnalyticsEventResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::edgify::CreateAnalyticsEventResponse>> AsyncCreateEvent(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::edgify::CreateAnalyticsEventResponse>>(AsyncCreateEventRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::edgify::CreateAnalyticsEventResponse>> PrepareAsyncCreateEvent(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::edgify::CreateAnalyticsEventResponse>>(PrepareAsyncCreateEventRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void CreateEvent(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest* request, ::edgify::CreateAnalyticsEventResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void CreateEvent(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest* request, ::edgify::CreateAnalyticsEventResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void CreateEvent(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest* request, ::edgify::CreateAnalyticsEventResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::edgify::CreateAnalyticsEventResponse>* AsyncCreateEventRaw(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::edgify::CreateAnalyticsEventResponse>* PrepareAsyncCreateEventRaw(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CreateEvent_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CreateEvent(::grpc::ServerContext* context, const ::edgify::CreateAnalyticsEventRequest* request, ::edgify::CreateAnalyticsEventResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CreateEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CreateEvent() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CreateEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateEvent(::grpc::ServerContext* /*context*/, const ::edgify::CreateAnalyticsEventRequest* /*request*/, ::edgify::CreateAnalyticsEventResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateEvent(::grpc::ServerContext* context, ::edgify::CreateAnalyticsEventRequest* request, ::grpc::ServerAsyncResponseWriter< ::edgify::CreateAnalyticsEventResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CreateEvent<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_CreateEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_CreateEvent() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::edgify::CreateAnalyticsEventRequest, ::edgify::CreateAnalyticsEventResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::edgify::CreateAnalyticsEventRequest* request, ::edgify::CreateAnalyticsEventResponse* response) { return this->CreateEvent(context, request, response); }));}
    void SetMessageAllocatorFor_CreateEvent(
        ::grpc::experimental::MessageAllocator< ::edgify::CreateAnalyticsEventRequest, ::edgify::CreateAnalyticsEventResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::edgify::CreateAnalyticsEventRequest, ::edgify::CreateAnalyticsEventResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_CreateEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateEvent(::grpc::ServerContext* /*context*/, const ::edgify::CreateAnalyticsEventRequest* /*request*/, ::edgify::CreateAnalyticsEventResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* CreateEvent(
      ::grpc::CallbackServerContext* /*context*/, const ::edgify::CreateAnalyticsEventRequest* /*request*/, ::edgify::CreateAnalyticsEventResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* CreateEvent(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::edgify::CreateAnalyticsEventRequest* /*request*/, ::edgify::CreateAnalyticsEventResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_CreateEvent<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_CreateEvent<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CreateEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CreateEvent() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CreateEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateEvent(::grpc::ServerContext* /*context*/, const ::edgify::CreateAnalyticsEventRequest* /*request*/, ::edgify::CreateAnalyticsEventResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CreateEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CreateEvent() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CreateEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateEvent(::grpc::ServerContext* /*context*/, const ::edgify::CreateAnalyticsEventRequest* /*request*/, ::edgify::CreateAnalyticsEventResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCreateEvent(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_CreateEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_CreateEvent() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CreateEvent(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_CreateEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CreateEvent(::grpc::ServerContext* /*context*/, const ::edgify::CreateAnalyticsEventRequest* /*request*/, ::edgify::CreateAnalyticsEventResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* CreateEvent(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* CreateEvent(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CreateEvent : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CreateEvent() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::edgify::CreateAnalyticsEventRequest, ::edgify::CreateAnalyticsEventResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::edgify::CreateAnalyticsEventRequest, ::edgify::CreateAnalyticsEventResponse>* streamer) {
                       return this->StreamedCreateEvent(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CreateEvent() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CreateEvent(::grpc::ServerContext* /*context*/, const ::edgify::CreateAnalyticsEventRequest* /*request*/, ::edgify::CreateAnalyticsEventResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCreateEvent(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::edgify::CreateAnalyticsEventRequest,::edgify::CreateAnalyticsEventResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CreateEvent<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CreateEvent<Service > StreamedService;
};

}  // namespace edgify


#endif  // GRPC_analytics_2eproto__INCLUDED
