// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: analytics.proto

#include "analytics.pb.h"
#include "analytics.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace edgify {

static const char* AnalyticsService_method_names[] = {
  "/edgify.AnalyticsService/CreateEvent",
};

std::unique_ptr< AnalyticsService::Stub> AnalyticsService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AnalyticsService::Stub> stub(new AnalyticsService::Stub(channel, options));
  return stub;
}

AnalyticsService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CreateEvent_(AnalyticsService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AnalyticsService::Stub::CreateEvent(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest& request, ::edgify::CreateAnalyticsEventResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::edgify::CreateAnalyticsEventRequest, ::edgify::CreateAnalyticsEventResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CreateEvent_, context, request, response);
}

void AnalyticsService::Stub::experimental_async::CreateEvent(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest* request, ::edgify::CreateAnalyticsEventResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::edgify::CreateAnalyticsEventRequest, ::edgify::CreateAnalyticsEventResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateEvent_, context, request, response, std::move(f));
}

void AnalyticsService::Stub::experimental_async::CreateEvent(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest* request, ::edgify::CreateAnalyticsEventResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CreateEvent_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::edgify::CreateAnalyticsEventResponse>* AnalyticsService::Stub::PrepareAsyncCreateEventRaw(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::edgify::CreateAnalyticsEventResponse, ::edgify::CreateAnalyticsEventRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CreateEvent_, context, request);
}

::grpc::ClientAsyncResponseReader< ::edgify::CreateAnalyticsEventResponse>* AnalyticsService::Stub::AsyncCreateEventRaw(::grpc::ClientContext* context, const ::edgify::CreateAnalyticsEventRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateEventRaw(context, request, cq);
  result->StartCall();
  return result;
}

AnalyticsService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AnalyticsService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AnalyticsService::Service, ::edgify::CreateAnalyticsEventRequest, ::edgify::CreateAnalyticsEventResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AnalyticsService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::edgify::CreateAnalyticsEventRequest* req,
             ::edgify::CreateAnalyticsEventResponse* resp) {
               return service->CreateEvent(ctx, req, resp);
             }, this)));
}

AnalyticsService::Service::~Service() {
}

::grpc::Status AnalyticsService::Service::CreateEvent(::grpc::ServerContext* context, const ::edgify::CreateAnalyticsEventRequest* request, ::edgify::CreateAnalyticsEventResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace edgify

