// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: analytics.proto

#ifndef PROTOBUF_INCLUDED_analytics_2eproto
#define PROTOBUF_INCLUDED_analytics_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_analytics_2eproto 

namespace protobuf_analytics_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_analytics_2eproto
namespace edgify {
class CreateAnalyticsEventRequest;
class CreateAnalyticsEventRequestDefaultTypeInternal;
extern CreateAnalyticsEventRequestDefaultTypeInternal _CreateAnalyticsEventRequest_default_instance_;
class CreateAnalyticsEventResponse;
class CreateAnalyticsEventResponseDefaultTypeInternal;
extern CreateAnalyticsEventResponseDefaultTypeInternal _CreateAnalyticsEventResponse_default_instance_;
}  // namespace edgify
namespace google {
namespace protobuf {
template<> ::edgify::CreateAnalyticsEventRequest* Arena::CreateMaybeMessage<::edgify::CreateAnalyticsEventRequest>(Arena*);
template<> ::edgify::CreateAnalyticsEventResponse* Arena::CreateMaybeMessage<::edgify::CreateAnalyticsEventResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace edgify {

// ===================================================================

class CreateAnalyticsEventRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:edgify.CreateAnalyticsEventRequest) */ {
 public:
  CreateAnalyticsEventRequest();
  virtual ~CreateAnalyticsEventRequest();

  CreateAnalyticsEventRequest(const CreateAnalyticsEventRequest& from);

  inline CreateAnalyticsEventRequest& operator=(const CreateAnalyticsEventRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CreateAnalyticsEventRequest(CreateAnalyticsEventRequest&& from) noexcept
    : CreateAnalyticsEventRequest() {
    *this = ::std::move(from);
  }

  inline CreateAnalyticsEventRequest& operator=(CreateAnalyticsEventRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateAnalyticsEventRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreateAnalyticsEventRequest* internal_default_instance() {
    return reinterpret_cast<const CreateAnalyticsEventRequest*>(
               &_CreateAnalyticsEventRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CreateAnalyticsEventRequest* other);
  friend void swap(CreateAnalyticsEventRequest& a, CreateAnalyticsEventRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CreateAnalyticsEventRequest* New() const final {
    return CreateMaybeMessage<CreateAnalyticsEventRequest>(NULL);
  }

  CreateAnalyticsEventRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CreateAnalyticsEventRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CreateAnalyticsEventRequest& from);
  void MergeFrom(const CreateAnalyticsEventRequest& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateAnalyticsEventRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:edgify.CreateAnalyticsEventRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_analytics_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CreateAnalyticsEventResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:edgify.CreateAnalyticsEventResponse) */ {
 public:
  CreateAnalyticsEventResponse();
  virtual ~CreateAnalyticsEventResponse();

  CreateAnalyticsEventResponse(const CreateAnalyticsEventResponse& from);

  inline CreateAnalyticsEventResponse& operator=(const CreateAnalyticsEventResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CreateAnalyticsEventResponse(CreateAnalyticsEventResponse&& from) noexcept
    : CreateAnalyticsEventResponse() {
    *this = ::std::move(from);
  }

  inline CreateAnalyticsEventResponse& operator=(CreateAnalyticsEventResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateAnalyticsEventResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreateAnalyticsEventResponse* internal_default_instance() {
    return reinterpret_cast<const CreateAnalyticsEventResponse*>(
               &_CreateAnalyticsEventResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(CreateAnalyticsEventResponse* other);
  friend void swap(CreateAnalyticsEventResponse& a, CreateAnalyticsEventResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CreateAnalyticsEventResponse* New() const final {
    return CreateMaybeMessage<CreateAnalyticsEventResponse>(NULL);
  }

  CreateAnalyticsEventResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CreateAnalyticsEventResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CreateAnalyticsEventResponse& from);
  void MergeFrom(const CreateAnalyticsEventResponse& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreateAnalyticsEventResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:edgify.CreateAnalyticsEventResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_analytics_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CreateAnalyticsEventRequest

// string name = 1;
inline void CreateAnalyticsEventRequest::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CreateAnalyticsEventRequest::name() const {
  // @@protoc_insertion_point(field_get:edgify.CreateAnalyticsEventRequest.name)
  return name_.GetNoArena();
}
inline void CreateAnalyticsEventRequest::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:edgify.CreateAnalyticsEventRequest.name)
}
#if LANG_CXX11
inline void CreateAnalyticsEventRequest::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:edgify.CreateAnalyticsEventRequest.name)
}
#endif
inline void CreateAnalyticsEventRequest::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:edgify.CreateAnalyticsEventRequest.name)
}
inline void CreateAnalyticsEventRequest::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:edgify.CreateAnalyticsEventRequest.name)
}
inline ::std::string* CreateAnalyticsEventRequest::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:edgify.CreateAnalyticsEventRequest.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CreateAnalyticsEventRequest::release_name() {
  // @@protoc_insertion_point(field_release:edgify.CreateAnalyticsEventRequest.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CreateAnalyticsEventRequest::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:edgify.CreateAnalyticsEventRequest.name)
}

// -------------------------------------------------------------------

// CreateAnalyticsEventResponse

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace edgify

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_analytics_2eproto
